graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "Z"
      graphics [
         x 1263
         y 654
      ]
   ]
   node [
      id 1
      label "Z"
      graphics [
         x 1129
         y 530
      ]
   ]
   node [
      id 2
      label "Z"
      graphics [
         x 917
         y 694
      ]
   ]
   node [
      id 3
      label "Z"
      graphics [
         x 774
         y 497
      ]
   ]
   node [
      id 4
      label "Z"
      graphics [
         x 605
         y 660
      ]
   ]
   node [
      id 5
      label "Z"
      graphics [
         x 605
         y 647
      ]
   ]
   node [
      id 6
      label "Z"
      graphics [
         x 688
         y 244
      ]
   ]
   node [
      id 7
      label "Z"
      graphics [
         x 956
         y 254
      ]
   ]
   node [
      id 9
      label "Z"
      graphics [
         x 1100
         y 377
      ]
   ]
   node [
      id 11
      label "Z"
      graphics [
         x 1302
         y 262
      ]
   ]
   node [
      id 13
      label "Z"
      graphics [
         x 1097
         y 205
      ]
   ]
   node [
      id 14
      label "Z"
      graphics [
         x 1069
         y 214
      ]
   ]
   node [
      id 16
      label "Z"
      graphics [
         x 887
         y 150
      ]
   ]
   node [
      id 25
      label "Z"
      graphics [
         x 527
         y 178
      ]
   ]
   node [
      id 26
      label "Z"
      graphics [
         x 430
         y 352
      ]
   ]
   node [
      id 27
      label "Z"
      graphics [
         x 587
         y 397
      ]
   ]
   node [
      id 31
      label "Z"
      graphics [
         x 505
         y 638
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 16
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 25
      label ""
      weight 1.0
   ]
   edge [
      source 25
      target 26
      label ""
      weight 1.0
   ]
   edge [
      source 26
      target 27
      label ""
      weight 1.0
   ]
   edge [
      source 27
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 27
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 31
      label ""
      weight 1.0
   ]
   edge [
      source 31
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 31
      target 26
      label ""
      weight 1.0
   ]
]