graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "Z"
      graphics [
         x 404
         y 147
      ]
   ]
   node [
      id 1
      label "Z"
      graphics [
         x 768
         y 147
      ]
   ]
   node [
      id 2
      label "Z"
      graphics [
         x 569
         y 439
      ]
   ]
   node [
      id 3
      label "Z"
      graphics [
         x 939
         y 379
      ]
   ]
   node [
      id 4
      label "Z"
      graphics [
         x 677
         y 670
      ]
   ]
   node [
      id 6
      label "Z"
      graphics [
         x 541
         y 664
      ]
   ]
   node [
      id 7
      label "Z"
      graphics [
         x 155
         y 238
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 2
      label ""
      weight 1.0
   ]
]