graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 13
      label "P"
      graphics [
         x 776
         y 320
      ]
   ]
   node [
      id 14
      label "N"
      graphics [
         x 1018
         y 320
      ]
   ]
   node [
      id 23
      label "N"
      graphics [
         x 776
         y 562
      ]
   ]
   node [
      id 24
      label "N"
      graphics [
         x 1018
         y 562
      ]
   ]
   node [
      id 25
      label "N"
      graphics [
         x 1260
         y 562
      ]
   ]
   node [
      id 26
      label "N"
      graphics [
         x 1502
         y 562
      ]
   ]
   node [
      id 27
      label "N"
      graphics [
         x 1744
         y 562
      ]
   ]
   node [
      id 31
      label "N"
      graphics [
         x 292
         y 804
      ]
   ]
   node [
      id 32
      label "N"
      graphics [
         x 534
         y 804
      ]
   ]
   node [
      id 33
      label "N"
      graphics [
         x 776
         y 804
      ]
   ]
   node [
      id 34
      label "N"
      graphics [
         x 1018
         y 804
      ]
   ]
   node [
      id 43
      label "N"
      graphics [
         x 776
         y 1046
      ]
   ]
   node [
      id 105
      label "P"
      graphics [
         x 779
         y 291
      ]
   ]
   node [
      id 114
      label "P"
      graphics [
         x 1645
         y 139
      ]
   ]
   node [
      id 22
      label "N"
      graphics [
         x 534
         y 562
      ]
   ]
   edge [
      source 23
      target 24
      label ""
      weight 1.0
   ]
   edge [
      source 24
      target 25
      label ""
      weight 1.0
   ]
   edge [
      source 25
      target 26
      label ""
      weight 1.0
   ]
   edge [
      source 26
      target 27
      label ""
      weight 1.0
   ]
   edge [
      source 49
      target 59
      label ""
      weight 1.0
   ]
   edge [
      source 48
      target 58
      label ""
      weight 1.0
   ]
   edge [
      source 47
      target 57
      label ""
      weight 1.0
   ]
   edge [
      source 47
      target 48
      label ""
      weight 1.0
   ]
   edge [
      source 46
      target 56
      label ""
      weight 1.0
   ]
   edge [
      source 45
      target 55
      label ""
      weight 1.0
   ]
   edge [
      source 44
      target 54
      label ""
      weight 1.0
   ]
   edge [
      source 44
      target 45
      label ""
      weight 1.0
   ]
   edge [
      source 43
      target 53
      label ""
      weight 1.0
   ]
   edge [
      source 43
      target 44
      label ""
      weight 1.0
   ]
   edge [
      source 42
      target 52
      label ""
      weight 1.0
   ]
   edge [
      source 42
      target 43
      label ""
      weight 1.0
   ]
   edge [
      source 41
      target 51
      label ""
      weight 1.0
   ]
   edge [
      source 40
      target 50
      label ""
      weight 1.0
   ]
   edge [
      source 40
      target 41
      label ""
      weight 1.0
   ]
   edge [
      source 100
      target 101
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 114
      label ""
      weight 1.0
   ]
   edge [
      source 116
      target 117
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 34
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 43
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 33
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 31
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 105
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 32
      label ""
      weight 1.0
   ]
   edge [
      source 22
      target 23
      label ""
      weight 1.0
   ]
]